# .upptimerc.yml
owner: khoi-ttc
repo: sivi_up
sites:
  - name: Mainframe
    url: $khoinet.ddns.net
    type: globalping
    location: Singapore
  - name: Middleman
    url: https://khoinet.dpdns.org
    method: GET
  - name: Immich
    url: https://photo.khoinet.dpdns.org
    method: GET
  - name: Jellyfin
    url: https://films.khoinet.dpdns.org
    method: GET
  - name: File Server
    url: https://file.khoinet.dpdns.org
    method: GET
  - name: ConvertX
    url: https://convert.khoinet.dpdns.org
    method: GET

status-page:
  title: Sivi oof checker
  description: Check server con song hay ko 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/khoi-ttc/sivi_uptime
